# Generated by Django 5.1.6 on 2025-04-25 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interacoes', '0003_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='mensagem_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interacoes.mensagem'),
        ),
    ]
