# Generated by Django 5.1.6 on 2025-04-25 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interacoes', '0004_mensagem_mensagem_anterior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='mensagem_anterior',
        ),
    ]
