# Generated by Django 5.2 on 2025-04-26 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interacoes', '0006_remove_mensagem_carro_remove_mensagem_destinatario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='conversa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interacoes.conversa'),
        ),
    ]
