# Generated by Django 5.2 on 2025-04-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interacoes', '0007_alter_mensagem_conversa'),
    ]

    operations = [
    ]
