# Generated by Django 5.2 on 2025-04-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_photo_car_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='plate',
        ),
        migrations.AddField(
            model_name='car',
            name='km',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
