# Generated by Django 5.1.6 on 2025-04-06 01:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_plate_car_km'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='carros_favoritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
