name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Install Node.js dependencies
      run: npm install

    - name: Run Cypress tests on production
      run: |
        npx wait-on https://match2autos.azurewebsites.net
        npx cypress run --config baseUrl=https://match2autos.azurewebsites.net

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test  # Só executa se os testes passarem

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Clean sensitive/testing files
      run: |
        cd MATCHAUTOS/
        rm -f db.sqlite3
        rm -f .env
        cd ..

    - name: Zip artifact for deployment
      run: |
        cd MATCHAUTOS/
        zip release.zip ./* -r
        cd ..
        mv MATCHAUTOS/release.zip .

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'match2autos'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: release.zip
