name: Build and deploy Python app to Azure Web App - match2autos

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm ci

      - name: Apply migrations and start server
        run: |
          cd MATCHAUTOS
          python manage.py migrate
          nohup python manage.py runserver 0.0.0.0:8000 &
          sleep 10
          npx wait-on http://localhost:8000
          cd ..

      - name: Run Cypress tests
        run: |
          npx cypress run --config baseUrl=http://localhost:8000

      - name: Clean test files
        run: |
          rm -f MATCHAUTOS/.env
          rm -f cypress.config.js
          rm -f package-lock.json
          rm -f package.json
          rm -rf cypress

      - name: Zip artifact for deployment
        run: |
          cd MATCHAUTOS
          zip -r ../release.zip ./*
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'match2autos'
          slot-name: 'Production'
          package: release.zip
