# .github/workflows/deploy-azure.yml
name: Build & Deploy Python app to Azure Web App – matchautos

on:
  push:
    branches: [ main ]        # branch “produção”
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (Azure App Service suporta ≤ 3.12)
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 1️⃣ Instala dependências dentro de MATCHAUTOS/
      - name: Install dependencies
        run: pip install -r MATCHAUTOS/requirements.txt

      # 2️⃣ Remove arquivos que atrapalham o deploy
      - name: Cleaning testing files
        run: |
          cd MATCHAUTOS/
          rm -f db.sqlite3 .env || true    # ignora se não existirem
          cd ..

      # (Opcional) rode seus testes aqui

      # 3️⃣ Compacta somente o diretório do projeto
      - name: Zip artifact for deployment
        run: |
          cd MATCHAUTOS/
          zip -r release.zip ./*
          cd ..
          mv MATCHAUTOS/release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ steps.deploy.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-app

      - run: unzip release.zip

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: "matchautos6"           # Web App criado na Azure
          slot-name: "Production"
          package: .                        # diretório raiz já contém o zip extraído
