# .github/workflows/deploy-azure.yml
name: Build & Deploy Python app to Azure Web App – matchautos

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 0. Checkout
      - uses: actions/checkout@v4

      # 1. Setup Python (versão igual à do Web App)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 2. Instalar dependências (requirements.txt fica na raiz do repo)
      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install gunicorn  # garante que o entry‑point exista

      # 3. Collect static → cria pasta staticfiles/
      - name: Django collectstatic
        run: |
          python manage.py collectstatic --noinput

      # 4. Copiar MEDIA (se existir) para dentro do pacote
      - name: Include media folder
        run: |
          if [ -d media ]; then
            echo "Copying media/ into package…"
          else
            mkdir media
          fi

      # 5. Empacotar TUDO que o Azure precisa: código + static + media
      - name: Zip artifact
        run: |
          zip -r release.zip . -x '.git/*'

      - uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ steps.deploy.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      # 6. Baixar artefato
      - uses: actions/download-artifact@v4
        with:
          name: python-app

      - run: unzip -q release.zip

      # 7. Login Azure
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 8. Deploy
      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: matchautos6
          slot-name: Production
          package: .
